# Generated by Django 5.1.4 on 2025-01-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_images/default_image.jpg', upload_to='menu_images/'),
        ),
    ]
