# Generated by Django 5.1.4 on 2025-01-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_image'),
    ]

    operations = [
    ]
