# Generated by Django 5.1.4 on 2025-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_sample_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
